repository:
  name: mosura
  description: task management system
  topics: bugtracker, task
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master
  delete_branch_on_merge: true

  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: '#fc2929'
  - name: feature
    color: '#84b6eb'
    oldname: enhancement
  - name: task
    color: '#d93f0b'

  - name: help wanted
    color: '#159818'
  - name: low-priority
    color: '#fbca04'

  - name: needs-triage
    color: '#ededed'
    oldname: triage
  - name: needs-info
    color: '#cc317c'
    oldname: question
  - name: ready-for-human
    color: '#ededed'
    oldname: backlog
  - name: ready-for-agent
    color: '#ededed'
  - name: wontfix
    color: '#dbe19f'

  - name: blocked
    color: '#dbe19f'
  - name: in-progress
    color: '#0052cc'
  - name: in-review
    color: '#5319e7'

  - name: automerge
    color: '#d913a6'

branches:
  - name: master
    protection:
      required_status_checks:
        strict: false
        contexts:
          - WIP
          - dependency-review
          - docker-build-readme
          - docker-workflow
          - pre-commit
      enforce_admins: false
      required_linear_history: true
